### ISSUE TITLE
Popup doesn't close itself after update to v2.2

### ISSUE THREAD

**Issue by mystiquewolf** [jscher2000/switch-to-previous-active-tab#12]
I have the option `Keep list open in same window` unchecked. After the last update to v2.2 switching to a different tab (by clicking on its entry in the popup) no longer causes the popup to close itself automatically.

Stack trace:
```
Uncaught (in promise) TypeError: self.close is not a function
    gotoTab moz-extension://d4d50315-15f4-41c2-89a8-cebd1282b8ce/popup.js:464
    promise callback*gotoTab/< moz-extension://d4d50315-15f4-41c2-89a8-cebd1282b8ce/popup.js:455
    promise callback*gotoTab moz-extension://d4d50315-15f4-41c2-89a8-cebd1282b8ce/popup.js:454
    EventListener.handleEvent* moz-extension://d4d50315-15f4-41c2-89a8-cebd1282b8ce/popup.js:481
popup.js:464:11
```

I believe the issue is the addition of the `self` variable [HERE](https://github.com/jscher2000/switch-to-previous-active-tab/commit/4f75cb3893a13d5a0a7502245fb90b3cddfde984#diff-3df6958c77d615b266b54fcf12fadf313e7c1e4b168f0c61ea8c3424eb39eb8cR15), which returns string and causes [THIS](https://github.com/jscher2000/switch-to-previous-active-tab/blob/4f75cb3893a13d5a0a7502245fb90b3cddfde984/popup.js#L464) to fail.

**Comment by jscher2000** [comment]
Thank you, I should try not to code after 10pm. The fix should go live soon.

**Comment by mystiquewolf** [comment]
Yeah, been there, done that... :slightly_frowning_face:
